server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: http://192.168.136.100
      port: 8500
      discovery:
        hostname: localhost
        service-name: ${spring.application.name}