server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: cloud-provider-payment-consul
  cloud:
    consul:
      # consul注册中心地址
      host: http://192.168.136.100
      port: 8500
      discovery:
        hostname: http://192.168.136.100:8500/
        service-name: ${spring.application.name}